'use client'

import Link from 'next/link'
import { ArrowLeft, CheckCircle2, CircleAlert, ClipboardCheck, Flame, Target } from 'lucide-react'
import { ContentCard } from '@/components/ui/content-card'
import { useCommandCenter } from '@/lib/command-center-store'

export function WeeklyReviewWorkspace() {
  const { tasks, habits, notes } = useCommandCenter()
  const doneTasks = tasks.filter((task) => task.status === 'done').length
  const openTasks = tasks.filter((task) => task.status !== 'done').length
  const doneHabits = habits.filter((habit) => habit.doneToday).length
  return <div className="space-y-4"><div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><ReviewMetric icon={CheckCircle2} label="مهام مكتملة" value={doneTasks} tone="green" /><ReviewMetric icon={CircleAlert} label="تحتاج قرار" value={openTasks} tone="orange" /><ReviewMetric icon={Flame} label="عادات اليوم" value={doneHabits} tone="purple" /><ReviewMetric icon={Target} label="ملاحظات جديدة" value={notes.length} tone="blue" /></div><div className="grid grid-cols-1 gap-4 lg:grid-cols-12"><ContentCard className="lg:col-span-7" title="ماذا سار جيدًا؟" description="أشياء تستحق أن تلاحظها بدل ما تمر عليها"><div className="space-y-3"><ReviewLine text={`أكملت ${doneTasks} من مهامك الحالية.`} done /><ReviewLine text={`حافظت على ${doneHabits} عادات اليوم.`} done /><ReviewLine text={`${notes.filter((note) => note.pinned).length} ملاحظات مثبتة تقدر ترجع لها.`} done /></div></ContentCard><ContentCard className="lg:col-span-5" title="ما الذي يحتاج قرارًا؟" description="لا تنقل كل شيء تلقائيًا للأسبوع القادم"><div className="space-y-3"><ReviewLine text={`${openTasks} مهام مفتوحة تحتاج ترتيبًا.`} /><ReviewLine text="اختر عادة واحدة فقط لرفع الالتزام بها." /><ReviewLine text="حدد مساحة تركيز خالية من الإشعارات." /></div></ContentCard><ContentCard className="lg:col-span-12 bg-surface-dark text-surface-dark-foreground" title="قرار الأسبوع القادم" description="اقتراح واضح وقابل للتعديل"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><p className="text-xl font-semibold">حافظ على البساطة: مهمة عميقة واحدة كل صباح.</p><p className="mt-2 max-w-2xl text-sm leading-7 text-surface-dark-foreground/60">الاقتراح مبني على توزيع المهام الحالي، ويمكنك رفضه أو تعديله. المراجعة لا تغيّر بياناتك تلقائيًا.</p></div><Link href="/daily-plan" className="flex shrink-0 items-center justify-center gap-2 rounded-full bg-primary px-4 py-3 text-xs font-semibold text-primary-foreground">تعديل خطة اليوم <ArrowLeft className="h-4 w-4" /></Link></div></ContentCard></div></div>
}

function ReviewMetric({ icon: Icon, label, value, tone }: { icon: typeof CheckCircle2; label: string; value: number; tone: 'green' | 'orange' | 'purple' | 'blue' }) { const tones = { green: 'bg-positive text-positive-foreground', orange: 'bg-[#fff0dc] text-[#c77b18]', purple: 'bg-[#ebe8ff] text-[#6f5fe6]', blue: 'bg-accent text-accent-foreground' }; return <div className="rounded-3xl bg-card p-4"><span className={`flex h-9 w-9 items-center justify-center rounded-xl ${tones[tone]}`}><Icon className="h-4 w-4" /></span><p className="mt-4 text-xs text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div> }
function ReviewLine({ text, done = false }: { text: string; done?: boolean }) { return <div className="flex items-center gap-3 rounded-2xl bg-muted/70 px-3 py-3 text-sm"><span className={`flex h-6 w-6 items-center justify-center rounded-full ${done ? 'bg-positive text-positive-foreground' : 'bg-warning text-warning-foreground'}`}>{done ? <CheckCircle2 className="h-3.5 w-3.5" /> : <CircleAlert className="h-3.5 w-3.5" />}</span><span>{text}</span></div> }
void ClipboardCheck
